// Datos simulados de organizaciones (reemplazar con datos reales)
export const orgMockData = [
  { id: "1", name: "Mi Empresa SL", role: "Propietario" },
  { id: "2", name: "Proyecto Personal", role: "Propietario" },
  { id: "3", name: "Acme Corp", role: "Administrador" },
  { id: "4", name: "Startup Innovadora", role: "Colaborador" },
  { id: "5", name: "Consultora XYZ", role: "Propietario" },
  { id: "6", name: "Proyecto Comunitario", role: "Miembro" },
  { id: "7", name: "Tecnología Avanzada", role: "Propietario" },
  { id: "8", name: "Soluciones Digitales", role: "Colaborador" },
  { id: "9", name: "Innovación Global", role: "Administrador" },
  { id: "10", name: "Desarrollo Sostenible", role: "Miembro" },
  // { id: "11", name: "Consultoría Estratégica", role: "Propietario" },
  // { id: "12", name: "Servicios Profesionales", role: "Colaborador" },
  // { id: "13", name: "Grupo Empresarial", role: "Administrador" },
  // { id: "14", name: "Proyectos Internacionales", role: "Propietario" },
  // { id: "15", name: "Marketing Digital", role: "Colaborador" },
  // { id: "16", name: "Diseño Creativo", role: "Miembro" },
  // { id: "17", name: "Investigación Aplicada", role: "Propietario" },
  // { id: "18", name: "Logística Integral", role: "Administrador" },
  // { id: "19", name: "Comercio Electrónico", role: "Colaborador" },
  // { id: "20", name: "Educación Innovadora", role: "Propietario" },
  // { id: "21", name: "Salud Digital", role: "Miembro" },
  // { id: "22", name: "Finanzas Corporativas", role: "Administrador" },
  // { id: "23", name: "Arquitectura Moderna", role: "Propietario" },
  // { id: "24", name: "Energías Renovables", role: "Colaborador" },
  // { id: "25", name: "Telecomunicaciones", role: "Miembro" },
];
